## Import the libraries

In [426]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Import the dataset

In [427]:
dataset = pd.read_csv('./data/Social_Network_Ads.csv')
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [428]:
dataset.describe()

Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [429]:
dataset.isna().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [430]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [431]:
X[:5, :]

array([[   19, 19000],
       [   35, 20000],
       [   26, 43000],
       [   27, 57000],
       [   19, 76000]])

In [432]:
y[:5]

array([0, 0, 0, 0, 0])

## Pre-process data

In [433]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=0)

## Train the model

In [434]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(max_depth=5)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5)

## Evaluate model

In [435]:
train_accuracy = classifier.score(X_train, y_train)
print(f'Train accuracy = {round(train_accuracy, 3)*100}%')

test_accuracy = classifier.score(X_test, y_test)
print(f'Test accuracy = {round(test_accuracy, 3)*100}%')

Train accuracy = 94.3%
Test accuracy = 95.0%


## Predict

In [436]:
data = [
    [20, 50000],
    [30, 100000],
    [40, 150000],
]

In [437]:
classifier.predict(data)

array([0, 1, 1])