## Import the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Import the dataset

In [2]:
dataset = pd.read_csv('./data/Social_Network_Ads.csv')
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [3]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
X[:5, :]

array([[   19, 19000],
       [   35, 20000],
       [   26, 43000],
       [   27, 57000],
       [   19, 76000]])

In [5]:
y[:5]

array([0, 0, 0, 0, 0])

## Pre-process the data

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Train the model

In [7]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(max_depth=5)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5)

## Evaluate the model

In [8]:
train_accuracy = classifier.score(X_train, y_train)
print(f'Train accuracy = {round(train_accuracy, 3)*100}%')

test_accuracy = classifier.score(X_test, y_test)
print(f'Train accuracy = {round(test_accuracy, 3)*100}%')

Train accuracy = 94.3%
Train accuracy = 95.0%


## Predict

In [9]:
data = [
    [20, 50000],
    [30, 100000],
    [40, 150000],
]

In [10]:
prediction = classifier.predict(data)

display(prediction)

array([0, 1, 1])