## Import the libraries

In [79]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Import the dataset

In [80]:
dataset = pd.read_csv('./data/Social_Network_Ads.csv')
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [81]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [82]:
X[:5, :]

array([[   19, 19000],
       [   35, 20000],
       [   26, 43000],
       [   27, 57000],
       [   19, 76000]])

In [83]:
y[:5]

array([0, 0, 0, 0, 0])

## Pre-process data

In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [85]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [86]:
X_train[:5, :]

array([[ 1.09667337, -0.11947427],
       [-1.01047197,  0.58033255],
       [ 0.42621803,  0.64118532],
       [ 0.71355603, -1.42780876],
       [-0.2442373 , -0.66714917]])

## Train the model

In [87]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(X_train, y_train)

KNeighborsClassifier()

## Evaluate model

In [88]:
train_accuracy = classifier.score(X_train, y_train)
print(f'Train accuracy = {round(train_accuracy, 4)*100}%')

test_accuracy = classifier.score(X_test, y_test)
print(f'Train accuracy = {round(test_accuracy, 4)*100}%')

Train accuracy = 92.0%
Train accuracy = 91.0%


## Predict

In [89]:
data = [
    [20, 50000],
    [30, 100000],
    [40, 150000],
]

In [90]:
data_scaled = sc.transform(data)
prediction = classifier.predict(data_scaled)

display(prediction)

array([0, 1, 1])