## Import the libraries

In [147]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Import the dataset

In [148]:
dataset = pd.read_csv('./data/Social_Network_Ads.csv')
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [149]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [150]:
X[:5, :]

array([[   19, 19000],
       [   35, 20000],
       [   26, 43000],
       [   27, 57000],
       [   19, 76000]])

In [151]:
y[:5]

array([0, 0, 0, 0, 0])

## Pre-process data

In [152]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [153]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [154]:
X_train[:5, :]

array([[ 1.78143576,  1.03440106],
       [-0.9532244 ,  1.5953454 ],
       [ 0.41410568, -0.44176828],
       [-1.539223  , -0.41224489],
       [ 1.78143576,  1.89057927]])

## Train the model

In [155]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf')
classifier.fit(X_train, y_train)

SVC()

## Evaluate model

In [156]:
train_accuracy = classifier.score(X_train, y_train)
print(f'Train accuracy = {round(train_accuracy, 4)*100}%')

test_accuracy = classifier.score(X_test, y_test)
print(f'Test accuracy = {round(test_accuracy, 4)*100}%')

Train accuracy = 91.0%
Test accuracy = 91.0%


## Predict

In [157]:
data = [
    [20, 50000],
    [30, 100000],
    [40, 150000],
]

In [158]:
data_scaled = sc.transform(data)
prediction = classifier.predict(data_scaled)

display(prediction)

array([0, 0, 1])